name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs exactly every 12 hours (midnight & noon UTC)
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Ensures the repo is available

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Ramprasanth7119
          output_path: dist/pacman-contribution-graph.svg  # Ensure correct output directory

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist  # Ensure the correct output directory is pushed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
